version: "3.6"

services:
  server:
    image: "${REGISTRY_NAME}/chatrooms/server:latest"
  gateway:
    image: "${REGISTRY_NAME}/chatrooms/client:latest"
    env_file:
      - gateway.env
    environment:
      - VIRTUAL_PORT=${GATEWAY_PORT:-4121}
    expose:
      - ${GATEWAY_PORT:-4121}
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
