version: "3.6"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT:-5000}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        CLIENT_PORT: ${CLIENT_PORT:-4121}
    ports:
      - "${CLIENT_PORT:-4121}:${CLIENT_PORT:-4121}"
