version: "3.6"

services:
  server:
    expose:
      - 5000
  client:
    environment:
      # node environment variables
      NODE_ENV: production
      PORT: 4123
      API_URL: http://server:5000
    ports:
      - "8000:4123"
