version: "3.6"

services:
  server:
    expose:
      - ${SERVER_PORT:-5000}
    environment:
      # to display print() in docker logs
      - PYTHONUNBUFFERED=1
    networks:
      - chatrooms_net
  gateway:
    environment:
      # node environment variables
      NODE_ENV: production
      GATEWAY_PORT: ${GATEWAY_PORT:-4121}
      SERVER_URL: http://server:${SERVER_PORT:-5000}
    depends_on:
      - server
    networks:
      - chatrooms_net

networks:
  chatrooms_net:
    driver: bridge
