version: "3.6"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT:-5000}
  gateway:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        GATEWAY_PORT: ${GATEWAY_PORT:-4121}
    ports:
      - "${GATEWAY_PORT:-4121}:${GATEWAY_PORT:-4121}"
