name: Deploy

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  deplpoy:
    name: Deploy to docker host
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Push deployment scripts
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "deploy.sh,docker-compose.yml,docker-compose.deployment.yml"
          target: /home/${{ secrets.USERNAME }}/chatrooms
      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        env:
          PROXY_URL: http://${{ secrets.HOST }}:8000
          REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          envs: PROXY_URL,REGISTRY_NAME
          script_stop: true
          script: |
            export PROXY_URL=$PROXY_URL
            export REGISTRY_NAME=$REGISTRY_NAME
            cd /home/${{ secrets.USERNAME }}/chatrooms
            chmod +x deploy.sh
            ./deploy.sh
