name: Python Server

defaults:
  run:
    shell: bash
    working-directory: server

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server.yml"
  pull_request:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server.yml"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        run: |
          python -m unittest -v
